version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    environment:
      SA_PASSWORD: "LitterMonitoring1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1443:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  fastapi:
    build: ./FastApi
    ports:
      - "8000:8000"
    volumes:
      - ./FastApi:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

volumes:
  mssql-data:
